### ISSUE TITLE
Adds files to project root instead of /src

### ISSUE THREAD

**Issue by michaelaflores** [brandonrninefive/add-redux#1]
It would be nice if there was an option to put these files inside /src instead of putting them at the root of the project. Many projects, especially those created with create-react-app, typically have some concept of a directory in which all of the actual project code sits, so I think this would benefit many users.

**Comment by brandontruggles** [comment]
@michaelaflores Thanks for the feedback! I agree. I think the best way to approach this would be to add an optional --src flag to specify a source directory to dump the redux files/directories. Assuming nobody wants to take this issue before I get to it, I will work on this for the next release.

**Comment by michaelaflores** [comment]
@brandonrninefive I'd love to contribute to this. I'll aim to take a look this weekend. If you have any tips or pointers to pass along, let me know; otherwise will aim to have a PR up this weekend and go from there. If I have any questions for whatever reason, is there a better way to reach you than this thread?

**Comment by brandontruggles** [comment]
@michaelaflores A PR would be greatly appreciated. If you need to contact me further, feel free to DM me via Twitter or Email (see my GitHub bio/website).

You will need to add a --src option here: https://github.com/brandonrninefive/add-redux/blob/master/index.js#L113

Currently, this variable is used for the path to everything in the project: https://github.com/brandonrninefive/add-redux/blob/e845c06c53d7f0654670d2ccedc9d9899318d640/index.js#L116

Since that variable searches for a yarn.lock and package.json, you can't set that one to the new src directory. You will need to set a new variable and check if the specified directory exists as a sub directory of the project root, throwing an error otherwise.

How I imagine this feature: add-redux projectroot/ --src src/

**Comment by brandontruggles** [comment]
Hey @michaelaflores , if you no longer wish to work on this, please let me know, and I will put through the bug fix myself for verison 0.6.0. Thanks!

**Comment by michaelaflores** [comment]
Hey @brandonrninefive! sorry this completely fell off my radar unintentionally – I'd love to take a look over the next couple days. To make sure it moves along, I'll follow up via DM. 👍

**Comment by michaelaflores** [comment]
@brandonrninefive I've unfortunately still not been able to get to this. If you end up picking it up before me let me know, I don't want to delay you! But if I get a chance before you I'll follow up.

**Comment by brandontruggles** [comment]
Hey @michaelaflores no worries! I went ahead and closed out this issue myself for version 0.6.0. If you see any other room for improvements, feel free to open another issue. PRs are always welcome!
